### ISSUE TITLE
TheLounge eats the response of certain commands

### ISSUE THREAD

**Issue by szczot3k** [thelounge/thelounge#4234]
- _Node version:_  v12.18.3 (thelounge/thelounge:latest docker)
- _Browser version:_ Google Chrome 90.0.4430.212
- _Device, operating system:_ Windows 10 2004; Hosted on Ubuntu 20.04.2 LTS with Docker (`Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2`).
- _The Lounge version:_ v4.2.0 (docker)

---

Hi, I've noticed that TheLounge eats the response of certain commands, for example while checking for current users's mode.

- Command: `/mode szczot3k`, and also `/who szczot3k`
- Expected result: `+Rzi` (as per output of HexChat)
- Actual result: no reponse.

It's kinda annoying. Right now I had to check it through HexChat.

**Comment by brunnre8** [comment]
Acutally an upstream "bug" / missing feature

https://github.com/kiwiirc/irc-framework/blob/223577fae8107f3068ec03c70da42eea554dba9f/src/commands/handlers/user.js#L359-L362

```js
    RPL_UMODEIS: function(command, handler) {
        // handler.connection.umodes = the modes
        // TODO: this
    },
```

We need to fix it there first

**Comment by brunnre8** [comment]
relevant upstream PR: https://github.com/kiwiirc/irc-framework/pull/288

**Comment by moribellamy** [comment]
Looks like this is fixed in irc-framework 4.11.0. is this release worthy?

**Comment by brunnre8** [comment]
That version is already pulled in our master branch but this doesn't actually fix it yet no.
We also need to listen to the event emitted.

But yes, It'll probably end up in the next release, will this happen *RIGHT NOW*, probably not. It's not an end of the world bug.
